spring.application.name=Hospital-Management-System

# Port configuration
server.port=8081

# DB configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hospitalDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Pranav@2004}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql